### ISSUE TITLE
Problem with Migrating 

### ISSUE THREAD

**Issue by shr3nron** [ralli/bz2redmine#14]
Hi.

Is this any posibility to use this migration script to migrate from bugzilla witch is on oracle DB to redmine witch is on postgre ? 

Redmine version is  3.3.3.stable
Ruby version            2.3.1-p112
Rails version             4.2.6

**Comment by ralli** [comment]
currently this script supports only mysql. although the sql commands are pretty standard and may work with oracle and postgres as well. 

you will have to customize the script to use oracle and postgres ruby drivers.
